#!/bin/bash

echo "------ HOOK START - BUILD -------"

DIR="$(cut -d'-' -f3 <<<"$COMMIT_MSG")"
if [ -z "$DIR" ]
then
echo "Directory is empty! Exit with error!"
fi

docker build -t $IMAGE_NAME --build-arg DIR=$DIR .

echo "------ HOOK END   - BUILD -------"