#!/bin/bash

echo "------ HOOK START - BUILD -------"
printenv

# ENV VARs are set by the cloud.docker.com build process, and are available during automated builds, automated tests,
# and while executing hooks like here.
# DOCKER_TAG: the Docker repository tag being built.
# https://docs.docker.com/docker-hub/builds/advanced/

DIR="$(cut -d'_' -f1 <<<"$COMMIT_MSG")"
FILE="$(cut -d'_' -f2 <<<"$COMMIT_MSG")"
NAME="$(cut -d':' -f1 <<<"$IMAGE_NAME")"

docker build -t $NAME:$COMMIT_MSG --build-arg DIR=$DIR --build-arg FILE=$FILE .

echo "------ HOOK END   - BUILD -------"